# Generated by Django 5.2.7 on 2025-11-08 08:46

import sfd.common.encrypted
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=sfd.common.encrypted.EncryptedDateField(blank=True, max_length=180, null=True, original_max_length=10, verbose_name='Birthday'),
        ),
    ]
