# Generated by Django 5.2.7 on 2025-11-09 05:06

import sfd.common.encrypted
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0002_alter_person_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=sfd.common.encrypted.EncryptedCharField(blank=True, max_length=180, null=True, original_max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=sfd.common.encrypted.EncryptedCharField(blank=True, max_length=180, null=True, original_max_length=20, verbose_name='Phone Number'),
        ),
    ]
