# Generated by Django 5.2.7 on 2025-11-09 05:18

import sfd.common.encrypted
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0003_alter_person_mobile_number_alter_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_detail',
            field=sfd.common.encrypted.EncryptedTextField(blank=True, max_length=420, null=True, verbose_name='Address Detail'),
        ),
    ]
