# Generated by Django 5.2.7 on 2025-11-09 09:49

import sfd.common.encrypted
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0004_alter_person_address_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_detail',
            field=sfd.common.encrypted.EncryptedCharField(blank=True, max_length=448, null=True, original_max_length=256, verbose_name='Address Detail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=sfd.common.encrypted.EncryptedEmailField(blank=True, max_length=272, null=True, original_max_length=128, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=sfd.common.encrypted.EncryptedCharField(max_length=184, original_max_length=64, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name_kana',
            field=sfd.common.encrypted.EncryptedCharField(max_length=184, original_max_length=64, verbose_name='Family Name Kana'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name_romaji',
            field=sfd.common.encrypted.EncryptedCharField(blank=True, max_length=184, null=True, original_max_length=64, verbose_name='Family Name Romaji'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=sfd.common.encrypted.EncryptedCharField(blank=True, max_length=144, null=True, original_max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=sfd.common.encrypted.EncryptedCharField(max_length=184, original_max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_kana',
            field=sfd.common.encrypted.EncryptedCharField(max_length=184, original_max_length=64, verbose_name='Name Kana'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_romaji',
            field=sfd.common.encrypted.EncryptedCharField(blank=True, max_length=184, null=True, original_max_length=64, verbose_name='Name Romaji'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=sfd.common.encrypted.EncryptedCharField(blank=True, max_length=144, null=True, original_max_length=20, verbose_name='Phone Number'),
        ),
    ]
