"""
Django settings for sfd_prj project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from decouple import config

from .settings_log import LOGGING

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must be set in .env file - no default value for security
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1,sfd-whqr.onrender.com", cast=lambda v: [s.strip() for s in v.split(",")])


# Application definition

INSTALLED_APPS = [
    "sfd",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "sfd.common.middleware.RequestMiddleware",
]

ROOT_URLCONF = "sfd_prj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "sfd/templates"),
        ],  # Optional: List of directories for templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sfd_prj.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Base configuration - PostgreSQL as default database
if "DATABASE_URL" in os.environ:
    # 1. Use the environment variable if it exists (i.e., when on Render)
    db_config = dj_database_url.config(
        default=config("DATABASE_URL"),  # type: ignore
        conn_max_age=600,  # Optional: Sets connection age for persistent connections
        ssl_require=config("DB_SSL_REQUIRE", default=not DEBUG, cast=bool),
    )
    DATABASES = {
        "default": db_config,
        "postgres": db_config.copy(),
    }
    DATABASES["postgres"]["TEST"] = {
        "MIRROR": "default",
    }
    # Optional: If you want to log the connection being used
    print("Using Production Database from DATABASE_URL")
else:
    # 2. Fallback to local settings from .env for development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("PGDATABASE"),
            "USER": config("PGUSER"),
            "PASSWORD": config("PGPASSWORD"),
            "HOST": config("PGHOST", default="localhost"),
            "PORT": config("PGPORT", default="5432"),
            "CONN_MAX_AGE": 60,  # Keep connections alive for 60 seconds
            "TEST": {
                "NAME": "test_default",
            },
        },
        "postgres": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("PGDATABASE"),
            "USER": config("PGUSER"),
            "PASSWORD": config("PGPASSWORD"),
            "HOST": config("PGHOST", default="localhost"),
            "PORT": config("PGPORT", default="5432"),
            "CONN_MAX_AGE": 60,  # Keep connections alive for 60 seconds
            "TEST": {
                "MIRROR": "default",
            },
        },
    }

DATABASE_ROUTERS = ["sfd_prj.db_routers.DbRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ja"

LANGUAGES = (
    ("en", "English"),
    ("ja", "Japanese"),
)

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Custom date/time formats - Direct override in settings
# These will override Django's default locale formats
DATE_FORMAT = "Y/m/d"
TIME_FORMAT = "H:i:s"
DATETIME_FORMAT = "Y/m/d H:i:s"
SHORT_DATE_FORMAT = "Y/m/d"
SHORT_DATETIME_FORMAT = "Y/m/d H:i"

# Input formats for form fields
DATE_INPUT_FORMATS = [
    "%Y-%m-%d",  # 2025-09-09
    "%Y/%m/%d",  # 2025/09/09
    "%Y-%m",  # 2025-09
    "%Y/%m",  # 2025/09
]

TIME_INPUT_FORMATS = [
    "%H:%M:%S",  # 14:30:45
    "%H:%M",  # 14:30
]

DATETIME_INPUT_FORMATS = [
    "%Y-%m-%d %H:%M:%S",  # 2025-09-09 14:30:45
    "%Y/%m/%d %H:%M:%S",  # 2025/09/09 14:30:45
    "%Y-%m-%d %H:%M",  # 2025-09-09 14:30
    "%Y/%m/%d %H:%M",  # 2025/09/09 14:30
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Enable WhiteNoise's GZip compression of static assets.
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

TEMP_DIR = os.path.join(BASE_DIR, "tmp")
os.makedirs(TEMP_DIR, exist_ok=True)

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# CSRF Settings
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True

# Session Settings
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = LOGIN_URL

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 2 * 7 * 24 * 60 * 60  # Cookie expires after 2 weeks of inactivity
SESSION_TIMEOUT = 30 * 60  # Session expires after 30 minutes of inactivity
SESSION_COOKIE_SECURE = True  # Secure cookies (HTTPS only)
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to cookies

DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB

LOGGING = LOGGING

# Field-level encryption settings for django-fernet-fields
# IMPORTANT: Store this key securely in your .env file, never commit to git
FERNET_KEYS = [config("FIELD_ENCRYPTION_KEY").encode()]  # type: ignore
